repos:
    - repo: https://github.com/ambv/black
        rev: 22.3.0
        hooks:
        -   id: black
            args: [--safe]
            language_version: python3.10

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: flake8
        -   id: requirements-txt-fixer
        -   id: trailing-whitespace

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.961
        hooks:
        -   id: mypy

    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            args: ["--profile", "black"]
